src/Entity/Lesson.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_persons;

    /**
     * @ORM\ManyToOne(targetEntity="training", inversedBy="lessons")
     */
    private $training;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="lessons")
     */
    private $instructeur;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="lesson")
     */
    private $registrations;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMaxPersons(): ?int
    {
        return $this->max_persons;
    }

    public function setMaxPersons(int $max_persons): self
    {
        $this->max_persons = $max_persons;

        return $this;
    }

    public function getTraining(): ?training
    {
        return $this->training;
    }

    public function setTraining(?training $training): self
    {
        $this->training = $training;

        return $this;
    }

    public function getInstructeur(): ?user
    {
        return $this->instructeur;
    }

    public function setInstructeur(?user $instructeur): self
    {
        $this->instructeur = $instructeur;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setLesson($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getLesson() === $this) {
                $registration->setLesson(null);
            }
        }

        return $this;
    }




}

src/Controller/InstructorController.php
<?php

namespace App\Controller;

use App\Entity\Lesson;
use App\Entity\Registration;
use App\Entity\User;
use App\Form\LessonType;
use App\Form\UserType;
use App\Repository\LessonRepository;
use App\Repository\RegistrationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/instructor")
 */
class InstructorController extends AbstractController
{
    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function editInstructor(Request $request, User $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $encoded = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($encoded);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }


    //LESSON CRUD

    /**
     * @Route("/lesson/plannen", name="lesson_plannen", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lesson = new Lesson();
        $user = $this->getUser();
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lesson->setInstructeur($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lesson);
            $entityManager->flush();

            return $this->redirectToRoute('lesson_overzicht');
        }

        return $this->render('views/instructor/new.html.twig', [
            'lesson' => $lesson,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/lesson/overzicht", name="lesson_overzicht", methods={"GET"})
     */
    public function index(LessonRepository $lessonRepository): Response
    {
        return $this->render('views/instructor/index.html.twig', [
            'lessons' => $lessonRepository->findAll(),
        ]);
    }

    /**
     * @Route("/overzicht/{id}", name="lesson_show", methods={"GET"})
     */
    public function show(Lesson $lesson, RegistrationRepository $registrationRepository): Response
    {
        return $this->render('views/instructor/show.html.twig', [
            'lesson' => $lesson,
            'registrations' => $registrationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/lesson/betaal/{id}", name="user_betalen", methods={"BETAAL"})
     */
    public function betaalt(Request $request, Registration $registration): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $registration->setPayment(true);
        $entityManager->flush();

        return $this->redirectToRoute('lesson_show', ['id' => $registration->getLesson()->getId()]);
    }

    /**
     * @Route("/overzicht/{id}/edit", name="lesson_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Lesson $lesson): Response
    {
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('lesson_overzicht');
        }

        return $this->render('views/instructor/edit.html.twig', [
            'lesson' => $lesson,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lesson_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Lesson $lesson): Response
    {
        if ($this->isCsrfTokenValid('delete' . $lesson->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lesson);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lesson_overzicht');
    }
}

templates/views/instructor/_delete_form.html.twig
<form class="d-inline" method="post" action="{{ path('lesson_delete', {'id': lesson.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lesson.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/views/instructor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <a class="btn btn-success d-inline" href="{{ path('lesson_overzicht') }}">back to list</a>
    <button class="btn btn-warning d-inline">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/views/instructor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lesson{% endblock %}

{% block body %}
    <div class="container">
        <h1>Edit Lesson</h1>

        {{ include('views/instructor/_form.html.twig', {'button_label': 'Update'}) }}
    </div>
{% endblock %}

templates/views/instructor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lesson index{% endblock %}

{% block body %}

    <div class="container">
{#        {% if is_granted("ROLE_INSTRUCTEUR") %}#}
{#            <h1>Lessen beheer</h1>#}
{#        {% elseif is_granted("ROLE_USER") %}#}
{#            <h1>Lessen overzicht</h1>#}

{#            {% for i in 1..13 %}#}
{#                <a class="is-active js-schedule-date btn btn-warning m-1"#}
{#                   style="list-style-type: none;"#}
{#                   href="{{ path('inschrijven', {date:date("now")|date_modify("+#{i} day")|date("d-m-Y")}) }}"> {{ date("now")|date_modify("+#{i} day")|date("D d M") }}#}
{#                </a>#}
{#            {% endfor %}#}
{#        {% endif %}#}

        <table class="table">
            <thead>
            <tr>
{#                <th>Image</th>#}
                <th>Id</th>
                <th>Time</th>
                <th>Date</th>
                <th>Location</th>
                <th>Max_persons</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for lesson in lessons %}
                {% if app.user.id == lesson.instructeur.id %}
                    <tr>
                        <td>{{ lesson.id }}</td>
                        <td>{{ lesson.time ? lesson.time|date('H:i') : '' }}</td>
                        <td>{{ lesson.date ? lesson.date|date('Y-m-d') : '' }}</td>
                        <td>{{ lesson.location }}</td>
                        <td>{{ lesson.maxPersons }}</td>
                        <td>
                            <a class="btn btn-success"
                               href="{{ path('lesson_show', {'id': lesson.id}) }}">show</a>
                            <a class="btn btn-warning"
                               href="{{ path('lesson_edit', {'id': lesson.id}) }}">edit</a>
                            {{ include('views/instructor/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% elseif is_granted("ROLE_USER") %}
                    <tr>
                        <td>
                            <img class="img-fluid" src="{{ asset('img/uploads/' ~ lesson.training.brochureFilename) }}"
                                 style="max-height: 200px; max-width: 250px">
                        </td>
                        <td>{{ lesson.id }}</td>
                        <td>{{ lesson.time ? lesson.time|date('H:i') : '' }}</td>
                        <td>{{ lesson.date ? lesson.date|date('Y-m-d') : '' }}</td>
                        <td>{{ lesson.location }}</td>
                        <td>{{ lesson.maxPersons }}</td>
                        <td>
                            <a class="btn btn-danger text-left"
                               href="{{ path('app_nu_inschrijvingen', {'id': lesson.id}) }}">Inschrijven</a>
                        </td>
                    </tr>
                {% endif %}
            {% else %}
                <tr>
                    <td colspan="6">Er zijn geen lessen</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/views/instructor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lesson{% endblock %}

{% block main %}
    <div class="container">
        <h1>Plan nieuwe les</h1>

        {{ include('views/instructor/_form.html.twig') }}

    </div>
{% endblock %}

templates/views/instructor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lesson{% endblock %}

{% block main %}
    <h1>Lesson</h1>
    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ lesson.id }}</td>
        </tr>
        <tr>
            <th>Time</th>
            <td>{{ lesson.time|date('H:i') }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ lesson.date|date('Y-m-d') }}</td>
        </tr>
        <tr>
            <th>Location</th>
            <td>{{ lesson.location }}</td>
        </tr>
        <tr>
            <th>Max_persons</th>
            <td>{{ lesson.maxPersons }}</td>
        </tr>
        </tbody>
    </table>

    <h1>Inschrijvingen</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Naam</th>
            <th>Payment</th>
        </tr>
        </thead>
        <tbody>
        {% for registration in registrations %}
            {% if registration.lesson.id == lesson.id %}
                <tr>
                    <td>{{ registration.user.firstname }} {{ registration.user.lastname }}</td>
                    <td>
                        {% if registration.payment == false %}
                            <form class="d-inline" method="post"
                                  action="{{ path('user_betalen', {'id': registration.id}) }}"
                                  onsubmit="return confirm('Weet je zeker dat de klant heeft betaald?');">
                                <input type="hidden" name="_method" value="BETAAL">
                                <button class="btn btn-warning d-inline">Betalen</button>
                            </form>
                        {% else %}
                            <p class="btn btn-success">Betaald</p>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}


        </tbody>
    </table>

    <a class="btn btn-outline-success" href="{{ path('lesson_overzicht') }}">back to list</a>

    <a class="btn btn-outline-warning" href="{{ path('lesson_edit', {'id': lesson.id}) }}">edit</a>

    {{ include('views/instructor/_delete_form.html.twig') }}
{% endblock %}